#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.dataman import Q
from cenai_core.grid import GridCLI

class PDACSummarization(Logger):
    logger_name = "cenai.system"

    @classmethod
    def main(cls) -> None:
        try:
            pdac_summarize = GridCLI(
                title="PDAC summarizer",
            )

            pdac_summarize()

        except Exception as e:
            cls.ERROR(e)
            exit(-1)


if __name__ == "__main__":
    PDACSummarization.main()