#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI, GridRunner

class PDACSummarize(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="PDAC summarizer",
            runner=GridRunner,
            search_name="profile",
            search_dir="%python/amc/pdac_summarizer/profile",
            search_pattern="*.yaml",
            search_type="file",
        )

    def __call__(self) -> None:
        self._cli()


if __name__ == "__main__":
    try:
        pdac_summarize = PDACSummarize()
        pdac_summarize()

    except Exception as error:
        PDACSummarize.ERROR(error)
        exit(-1)
