#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI, GridRunner

class PJSummarize(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="PJ summarizer",
            runner=GridRunner,
            search_name="profile",
            search_dir="%python/amc/pj_summarizer/profile",
            search_pattern="*.yaml",
            search_type="file",
        )

    def __call__(self) -> None:
        self._cli.invoke()


if __name__ == "__main__":
    try:
        pj_summarize = PJSummarize()
        pj_summarize()

    except Exception as error:
        PJSummarize.ERROR(error)
        exit(-1)
