#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI, GridRunner


class PDACClassify(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="PDAC classifier",
            runner=GridRunner,
            search_name="profile",
            search_dir="%python/amc/pdac_classifier/profile",
            search_pattern="*.yaml",
            search_type="file",
        )

    def __call__(self) -> None:
        self._cli.invoke()


if __name__ == "__main__":
    try:
        pdac_classify = PDACClassify()
        pdac_classify()

    except Exception as error:
        PDACClassify.ERROR(error)
        exit(-1)
