#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI

from pdac_recapper import PDACRecapper


class PDACRecap(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="PDAC recapper",
            runner=PDACRecapper,
            search_name="artifact",
            search_dir="%artifact",
            search_pattern="*",
            search_type="dir",
            search_filter=lambda path: path.name.endswith("-classifier")
        )

    def __call__(self) -> None:
        self._cli.invoke()


if __name__ == "__main__":
    try:
        pdac_recap = PDACRecap()
        pdac_recap()

    except Exception as e:
        PDACRecap.ERROR(e)
        exit(-1)
