#!/usr/bin/env python3
import argparse

from amc.pdac_classifier import PDACRecapper


class PDACRecap(PDACRecapper):
    def __init__(self):
        super().__init__()

    @classmethod
    def _get_args(cls) -> argparse.Namespace:
        parser = argparse.ArgumentParser(
            description="PDAC classification recapper"
        )

        return parser.parse_args()

    def __call__(self) -> None:
        self.export_excel()

if __name__ == "__main__":
    try:
        pdac_recap = PDACRecap()
        pdac_recap()
    except Exception as e:
        PDACRecap.ERROR(e)
