#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI, GridRunner


class PaperSummarization(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="Paper summarizer",
            runner=GridRunner,
            search_name="profile",
            search_dir="%python/nrf/paper_summarizer/profile",
            search_pattern="*.yaml",
            search_type="file",
        )

    def __call__(self) -> None:
        self._cli()


if __name__ == "__main__":
    try:
        papaer_summarize = PaperSummarization()
        papaer_summarize()

    except Exception as error:
        PaperSummarization.ERROR(error)
        exit(-1)
