services:
  posgres:
    image: postgres:latest
    container_name: cenai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    volumes:
    - /var/lib/docker_volumes/postgresql/data:/var/lib/postgresql/data
